### ISSUE TITLE
CUDA not detected in docker containers (so models cannot run in local agent)

### ISSUE THREAD

**Issue by ldorigo** [supervisely/supervisely#54]
Hello, 

See https://github.com/NVIDIA/nvidia-docker/issues/1447#issuecomment-757034464 : in recent versions of systemd, docker needs to be specially configured to allow containers to be aware of the GPU. 

I believe this is the cause of an error I get with multiple models when I try to run inference using my local agent, see the attached logs: 

[task_334537.log](https://github.com/supervisely/supervisely/files/7179723/task_334537.log)

For reference, this is the warning message I get when installing nvidia-container-toolkit on ArchLinux - it might have some relevant information for you:

```
Warning about nvidia containers!                                                                                                                                 
                                                                                                                                                                 
Systemd v247.2-2 introduced a unified cgroup change which has somewhat                                                                                           
broken nvidia-container's access to the handles in                                                                                                               
/sys/fs/cgroup/devices.                                                                                                                                          
                                                                                                                                                                 
If you are using Docker you will then need to explicitly allow access                                                                                            
to the nvidia devices like:                                                                                                                                      
                                                                                                                                                                 
docker run ... --gpus all --device /dev/nvidia0 --device \                                                                                                       
    /dev/nvidia-uvm --device /dev/nvidia-uvm-tools --device \                                                                                                    
    /dev/nvidiactl ...                                                                                                                                           
                                                                                                                                                                 
or by using a docker-compose which exposes the devices with:                                                                                                     

devices:
  - /dev/nvidia0:/dev/nvidia0
  - /dev/nvidiactl:/dev/nvidiactl
  - /dev/nvidia-modeset:/dev/nvidia-modeset
  - /dev/nvidia-uvm:/dev/nvidia-uvm
  - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools

See the link for more details:
https://github.com/NVIDIA/nvidia-docker/issues/1447#issuecomment-757034464
```

**Comment by leopiney** [comment]
Hi @ldorigo - I think I'm facing a similar issue using Fedora 35. The only way I managed to run nvidia-docker containers is enabling the `o-cgroups = true` as in [the first link you shared](https://github.com/NVIDIA/nvidia-docker/issues/1447#issuecomment-757034464) AND using the `--privileged` parameter.

So I had to do 2 things:

1. Modified the agent-updater.sh file[^1] so that it runs the Supervisely agent with privileged mode
2. Ensure that all the spawn containers by the agent also run in privileged mode

## Enabling the agent-update with privileged mode

I downloaded the agent-updater from the URL in the instructions given by Supervisely:

![image](https://user-images.githubusercontent.com/15099524/143606254-b4396674-d4e5-4a41-b241-db23707c19e9.png)

Then, I proceeded to modify the script adding the `--privileged` flag when it runs `docker run`:

```bash
# agent-updater.sh

echo 'Remove existing container if any...'
docker rm -fv "supervisely-agent-xxx" 2> /dev/null
docker run -it -d --name="supervisely-agent-xxx" --runtime=nvidia --privileged  \  # <- added --privileged
      --restart=unless-stopped \
      ...\
      -v "${AGENT_HOST_DIR}:/sly_agent" \
       \
      "${SUPERVISELY_AGENT_IMAGE}"
```

After this, you can start your agent by running `sh agent-updater.sh`.

## Making all task containers run in privileged mode

Then, when I thought I solved my issue, but I noticed that my agent was starting a different container for each task that it was running. Unfortunately, the privileged flag was not declared for those other containers, so if a task required GPU, it failed with the same error message as yours. So I ended up doing this:

1. Searched for the part of the code that spawns containers

https://github.com/supervisely/supervisely/blob/master/agent/src/worker/task_dockerized.py#L145-L176

2. Looking at the docker documentation, we need to add the `privileged=True` parameter, but since this is running in docker, we can't do that. So I created a simple docker image like this:

```docker
# Dockerfile
FROM supervisely/agent:latest

# Adds the privileged=True parameter to the containers.run function
RUN sed '153iprivileged=True,' /workdir/src/worker/task_dockerized.py > task_dockerized.py
# Replaces original file
RUN cp task_dockerized.py worker/task_dockerized.py                     
```

3. Then, we build the image

```bash
docker build -t supervisely-fedora .
```

4. And finally, we replace the regular supervisely agent image with the new one we just built. Run `sh agent-updater.sh` again to replace the previous agent.

```bash
# agent-updater.sh

echo 'Remove existing container if any...'
docker rm -fv "supervisely-agent-xxx" 2> /dev/null
docker run -it -d --name="supervisely-agent-xxx" --runtime=nvidia --privileged  \
      --restart=unless-stopped \
      ...\
      -v "${AGENT_HOST_DIR}:/sly_agent" \
       \
      "supervisely-fedora"  # <- replaced image name
```

## Testing if it works

In order to test it, I had to `docker exec -it <hash> bash` the containers generated by the Supervisely Agent and run `nvidia-smi` to verify that my GPU was indeed there.

Please let me know if this worked out for you. I'll make a PR with the changes so that the docker image trick is not necessary, but I'm sure I'll f*ck things up for the rest of us if everyone runs privileged containers.

[^1]: I got the agent-updater.sh from the Supervisely instructions

**Comment by p-vdp** [comment]
Similar issue here trying to run the supervisely agent container on Windows 11. I'm running Docker Desktop and an Ubuntu 20.04 distro in WSL 2. 

The Nvidia drivers appear to be included with Ubuntu 20.04, you only need to install the nvidia-docker2 package after adding the repo to your apt list. ([Instructions here.](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#installing-on-ubuntu-and-debian))

However, when I run `agent-updater.sh` I get this:

> docker: Error response from daemon: Unknown runtime specified nvidia.

I tried the [various methods](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html) for adding the runtime to docker but it never recognized it. Perhaps running a privileged container would work but I want to avoid doing that.

The workaround I found was simply to remove `--runtime=nvidia` from the `docker run` line in `agent-updater.sh`. Looks like it's working OK now!
